
def hasDiff(path) {
    try {
        sh "git diff-tree -r --exit-code --no-commit-id --name-only HEAD^ HEAD -- ${path}"
        return false
    } catch (e) {
        return true
    }
}

pipeline {
    agent any

    options {
        timeout(time: 30, unit: 'MINUTES')
    }

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'rm -rf node_modules; yarn install --frozen-lockfile --cache-folder .yarn'
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    if ( hasDiff("./apps/app-2") ) {
                        sh "yarn turbo run build --scope=@apps/app-2"
                    }
                }
            }
        }
    }
}
