
def hasDiff(path) {
    try {
        sh "git diff-tree -r --exit-code --no-commit-id --name-only HEAD^ HEAD -- ${path}"
        return false
    } catch (e) {
        return true
    }
}

def isDiff = hasDiff("./apps/app-2")

pipeline {
    agent any

    options {
        timeout(time: 30, unit: 'MINUTES')
    }

    stages {
        stage('Install Dependencies') {
            when {
                expression { isDiff }
            }
            steps {
                script {
                    sh 'rm -rf node_modules; yarn install --frozen-lockfile --cache-folder .yarn'
                }
            }
        }
        stage('Build') {
            when {
                expression { isDiff }
            }
            steps {
                script {
                    sh "yarn turbo run build --scope=@apps/app-2"
                }
            }
        }
    }
}
