
pipeline {
    agent { node { label 'linux && nodejs' }}

    options {
        timeout(time: 30, unit: 'MINUTES')
    }

    environment {

    }

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'rm -rf node_modules; yarn install --frozen-lockfile --cache-folder .yarn'
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    sh "yarn build --filter=${env.GIT_BRANCH}"
                }
            }
        }
    }
}
